# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Wolfman Family
email: canismarko@gmail.com
description: > # this means to ignore newlines until "baseurl"
  Welcome to the Wolfman family website. Keep up to date on our familial
  happenings, like the arrival of baby "sprout" in October.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://prettywolves.com" # the base hostname & protocol for your site
twitter_username: m3wolf
github_username:  canismarko

# Build settings
markdown: kramdown
